name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        cmake --build . --config ${{env.BUILD_TYPE}}
        ctest -C ${{env.BUILD_TYPE}}
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub's default token for authentication
      run: npx semantic-release
